name: Lotus canary deployment

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  install-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@lotus-install-snapshot'
          reaction: heart
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found @lotus-install-snapshot!'
        if: steps.check.outputs.triggered == 'true'
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@lotus-upgrade'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found @lotus-upgrade!'
        if: steps.check.outputs.triggered == 'true'
